### ISSUE TITLE
40 branch

### ISSUE THREAD

**Issue by tiawaz** [PowerDNS/pdns_recursor-ansible#13]
Basically the ame as in https://github.com/PowerDNS/pdns-ansible/issues/20

Installing from 40 branch on CentOS
```
  roles:
   - role: pdns_recursor-ansible
  vars:
    pdns_rec_installation_type: 'packages'
    pdns_rec_repo_provider: 'powerdns'
    pdns_rec_repo_branch: '40'
    pdns_rec_config:
      'allow-from': 'xxx.xxx.xxx.xxx'
      'local-address': '{{ ansible_eth0.ipv4.address }}:5300'
```

i ran into the following issue:

1) The packages use /etc/pdns-recursor as config dir, but the role defaults to /etc/powerdns
